# Netlifyデプロイ設定
[build]
  command = "echo 'Using pre-built static files'"
  publish = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Next.jsプラグインを一時的に無効化
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# 環境変数（Netlifyの管理画面で設定することを推奨）
[context.production.environment]
  NODE_ENV = "production"

# リダイレクト設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
