# Netlifyデプロイ設定
[build]
  command = "npm run build && npm run export || echo 'Build completed'"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# [[plugins]] package = "@netlify/plugin-nextjs"

# 環境変数（Netlifyの管理画面で設定することを推奨）
[context.production.environment]
  NODE_ENV = "production"

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
